@startuml 

title Lease annual slip to existing customer
actor MarinaManager

participant aSlip 
participant aBoat 

MarinaManager -> aSlip : leaseSlip(boat, startDate)
activate aSlip

aSlip -> aBoat : assignBoatToSlip()
activate aBoat
aBoat --> aSlip : boatDetails
deactivate aBoat

aSlip -> anAnnualLease : create(startDate)
activate anAnnualLease
anAnnualLease -> anAnnualLease : calculateFee()
anAnnualLease --> aSlip : endDate & fee
deactivate anAnnualLease

aSlip -> aCustomer : assignCustomer()
activate aCustomer
aCustomer --> aSlip : customer details
deactivate aCustomer

aSlip --> MarinaManager : lease details
deactivate aSlip

@enduml