@startuml 

title Lease daily slip to existing customer
actor MarinaManager

participant aSlip 
participant aBoat 

MarinaManager -> aSlip : leaseSlip(boat, startDate)
activate aSlip

aSlip -> aBoat : assignBoatToSlip()
activate aBoat
aBoat --> aSlip : boatDetails
deactivate aBoat

aSlip -> aDailyLease : create(startDate, numberOfDays)
activate aDailyLease
aDailyLease -> aDailyLease : calculateFee()
aDailyLease --> aSlip : endDate & fee
deactivate aDailyLease

aSlip -> aCustomer : assignCustomer()
activate aCustomer
aCustomer --> aSlip : customer details
deactivate aCustomer

aSlip --> MarinaManager : lease details
deactivate aSlip

@enduml